DROP DATABASE IF EXISTS PAZVEBOOST;
CREATE DATABASE PAZVEBOOST;
USE PAZVEBOOST;

CREATE TABLE CARRITO_COMPRA(
    COD_REF INT AUTO_INCREMENT PRIMARY KEY,
    COD_PRODCT INT NOT NULL,
    NOM_PRODCT VARCHAR(50) NOT NULL,
    CANTIDAD INT DEFAULT 1,
    ID_CL INT,
    FOREIGN KEY (ID_CL) REFERENCES CLIENTE(ID_CL)
);

CREATE TABLE CLIENTE(
    ID_CL INT AUTO_INCREMENT PRIMARY KEY,
    MAIL_CL VARCHAR(50) UNIQUE NOT NULL,
    CONTR_CL VARCHAR(255) NOT NULL,
    DIR_CL VARCHAR(100),
    CC_CL VARCHAR(20),
    TEL_CL VARCHAR(15),
    NOM_CL VARCHAR(50),
    CIU_CL VARCHAR(50)
);

CREATE TABLE VERIFICACION(
    ID_VER INT AUTO_INCREMENT PRIMARY KEY,
    ID_CL INT NOT NULL,
    CODIGO VARCHAR(10) NOT NULL,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_CL) REFERENCES CLIENTE(ID_CL)
);
