DROP DATABASE IF EXISTS PAZVEBOOST;
CREATE DATABASE PAZVEBOOST;
USE PAZVEBOOST;

CREATE TABLE CARRITO_COMPRA(
    COD_REF INT AUTO_INCREMENT PRIMARY KEY,
    COD_PRODCT INT,
    NOM_PRODCT VARCHAR (20)
);

CREATE TABLE CLIENTE(
    ID_CL INT AUTO_INCREMENT PRIMARY KEY,
    MAIL_CL VARCHAR (30) UNIQUE,
    CONTR_CL VARCHAR (20) UNIQUE,
    DIR_CL VARCHAR (20),
    CC_CL VARCHAR (15),
    TEL_CL CHAR(10),
    NOM_CL VARCHAR (20),
    CIU_CL VARCHAR(50),
    COD_REF INT,
    FOREIGN KEY (COD_REF) REFERENCES CARRITO_COMPRA(COD_REF)
);

CREATE TABLE VERIFICACION(
    ID_CL INT AUTO_INCREMENT PRIMARY KEY,
    CONTR_CL VARCHAR (20),
    MAIL_CL VARCHAR (20),
    FOREIGN KEY (MAIL_CL) REFERENCES CLIENTE(MAIL_CL),
    FOREIGN KEY (CONTR_CL) REFERENCES CLIENTE(CONTR_CL)
);
